repos:
-   repo: local
    hooks:
    -   id: isort
        name: iSort - Sort imports
        entry: isort
        language: python
        types: [python]
        pass_filenames: true
        additional_dependencies:
            - isort
    -   id: black
        name: Black - Auto-formatter
        entry: black
        language: python
        types: [ python ]
        pass_filenames: true
        additional_dependencies:
            - black
    -   id: flake8
        name: Flake8 - Enforce code style
        entry: black
        language: python
        types: [ python ]
        pass_filenames: true
        additional_dependencies:
            - flake8
            - flake8-docstrings